using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[RequireComponent(typeof(MeshFilter))]
[RequireComponent(typeof(MeshRenderer))]

public class TriangleMaker : MonoBehaviour
{

    [SerializeField]
    private Vector3 size = Vector3.one;

    private List<Material> materialList;


    // Update is called once per frame
    void Update()
    {
        //1. initialise mesh filter
        MeshFilter meshFilter = this.GetComponent<MeshFilter>();

        //2. initialise mesh builder
        MeshBuilder meshBuilder = new MeshBuilder(1);

        //3. build our triangle

        Vector3 p0 = new Vector3(size.x,  size.y, -size.z);
        Vector3 p1 = new Vector3(-size.x, size.y, -size.z);
        Vector3 p2 = new Vector3(-size.x, size.y,  size.z);

        meshBuilder.BuildTriangle(p0, p1, p2, 0);

        //4. mesh filter's mesh to the one generated by the mesh builder
        meshFilter.mesh = meshBuilder.CreateMesh();

        //5. initialise mesh renderer and assign material list to the mesh renderer's materials list
        MeshRenderer meshRenderer = this.GetComponent<MeshRenderer>();
        AddMaterials();
        meshRenderer.materials = materialList.ToArray();
    }

    private void AddMaterials()
    {
        Material redMaterial = new Material(Shader.Find("Specular"));
        redMaterial.color = Color.red;

        materialList = new List<Material>();
        materialList.Add(redMaterial);
    }
}
